//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hololens
{
    [Serializable]
    public class GetAIDataRequest : Message
    {
        public const string k_RosMessageName = "hololens_msgs/GetAIData";
        public override string RosMessageName => k_RosMessageName;

        public long point_x;
        public long point_y;

        public GetAIDataRequest()
        {
            this.point_x = 0;
            this.point_y = 0;
        }

        public GetAIDataRequest(long point_x, long point_y)
        {
            this.point_x = point_x;
            this.point_y = point_y;
        }

        public static GetAIDataRequest Deserialize(MessageDeserializer deserializer) => new GetAIDataRequest(deserializer);

        private GetAIDataRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.point_x);
            deserializer.Read(out this.point_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.point_x);
            serializer.Write(this.point_y);
        }

        public override string ToString()
        {
            return "GetAIDataRequest: " +
            "\npoint_x: " + point_x.ToString() +
            "\npoint_y: " + point_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
