//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hololens
{
    [Serializable]
    public class GetAIDataResponse : Message
    {
        public const string k_RosMessageName = "hololens_msgs/GetAIData";
        public override string RosMessageName => k_RosMessageName;

        public string class_name;
        public string instructions;
        public string model;

        public GetAIDataResponse()
        {
            this.class_name = "";
            this.instructions = "";
            this.model = "";
        }

        public GetAIDataResponse(string class_name, string instructions, string model)
        {
            this.class_name = class_name;
            this.instructions = instructions;
            this.model = model;
        }

        public static GetAIDataResponse Deserialize(MessageDeserializer deserializer) => new GetAIDataResponse(deserializer);

        private GetAIDataResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.class_name);
            deserializer.Read(out this.instructions);
            deserializer.Read(out this.model);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.class_name);
            serializer.Write(this.instructions);
            serializer.Write(this.model);
        }

        public override string ToString()
        {
            return "GetAIDataResponse: " +
            "\nclass_name: " + class_name.ToString() +
            "\ninstructions: " + instructions.ToString() +
            "\nmodel: " + model.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
