//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hololens
{
    [Serializable]
    public class AIDataMsg : Message
    {
        public const string k_RosMessageName = "hololens_msgs/AIData";
        public override string RosMessageName => k_RosMessageName;

        public string[] scene_names;

        public AIDataMsg()
        {
            this.scene_names = new string[0];
        }

        public AIDataMsg(string[] scene_names)
        {
            this.scene_names = scene_names;
        }

        public static AIDataMsg Deserialize(MessageDeserializer deserializer) => new AIDataMsg(deserializer);

        private AIDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.scene_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.scene_names);
            serializer.Write(this.scene_names);
        }

        public override string ToString()
        {
            return "AIDataMsg: " +
            "\nscene_names: " + System.String.Join(", ", scene_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
