//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hololens
{
    [Serializable]
    public class ImageMsg : Message
    {
        public const string k_RosMessageName = "hololens_msgs/Image";
        public override string RosMessageName => k_RosMessageName;

        public byte[] data;
        public uint width;
        public uint height;

        public ImageMsg()
        {
            this.data = new byte[0];
            this.width = 0;
            this.height = 0;
        }

        public ImageMsg(byte[] data, uint width, uint height)
        {
            this.data = data;
            this.width = width;
            this.height = height;
        }

        public static ImageMsg Deserialize(MessageDeserializer deserializer) => new ImageMsg(deserializer);

        private ImageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.width);
            serializer.Write(this.height);
        }

        public override string ToString()
        {
            return "ImageMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
